<?php

return [
    'Media'=>[
        'Upload',
        'Edit',
        'Delete',
        'List'
    ],
    'Menu'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Pages'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Testimonials'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Faqs'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Tailors'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Coupons'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],

    'Coupons'=>[
        'Create',
        'Edit',
        'Delete',
        'List',
    ],
    'Products'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Product_Fabrics'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Product_Sizes'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Kandora_Designs'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_fabrics'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_patterns'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_design_sleeves'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_sleeve_lengths'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_sleeve_buttons'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_neck_shapes'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_neck_front_lengths'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'khawar_neck_lengths'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_waist_shape_tights'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_type_crystals'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_size_crystals'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'kandora_amount_crystals'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Roles'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Users'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Email_Templates'=>[
        'Create',
        'Edit',
        'Delete',
        'List'
    ],
    'Theme_Settings'=>[
        'Edit',
        'List'
    ],
    'Orders'=>[
        'Edit',
        'List'
    ],
    'Product_ratings'=>[
        'Edit',
        'List'
    ],
    'Customers'=>[
        'Export',
        'List'
    ],
    'Contacts'=>[
        'Export',
        'List'
    ],
];
